### ISSUE TITLE
Installation failure: KeyError: u'id' in _parse_args_in_yunohost_format

### ISSUE THREAD

**Issue by mxmilkiib** [YunoHost-Apps/mopidy_ynh#12]
```
Yunohost encountered an internal error:/
Really sorry about that.
You should look for help on the forum or the chat to fix the situation, or report the bug on the bugtracker.
The following information might be useful for the person helping you:
Action

POST /apps
{"app":"https://github.com/YunoHost-Apps/mopidy_ynh/","args":"domain=xxxxxxxx.org&path=%2Fmopidy&admin_mopidy=xxxxxxxx&spotify_user=xxxxxxxx&spotify_pass=&spotify_id=&spotify_id_secret=&soundcloud_id=xxxxxxxx","label":"Mopidy"}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 485, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 592, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 358, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 755, in app_install
    args_odict = _parse_args_from_manifest(manifest, 'install', args=args_dict)
  File "/usr/lib/moulinette/yunohost/app.py", line 2392, in _parse_args_from_manifest
    return _parse_args_in_yunohost_format(args, action_args)
  File "/usr/lib/moulinette/yunohost/app.py", line 2665, in _parse_args_in_yunohost_format
    parser = ARGUMENTS_TYPE_PARSERS[question.get("type", "string")]()
KeyError: u'id'
```

**Comment by siwinter** [comment]
The app has been completely redesigned.
If this does not solve the problem, please open a new issue.
